name: Publish Crate

on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-version: [stable, beta, nightly, "1.70.0"]
    steps:
    - uses: actions/checkout@v4
    - name: Setup Rust ${{ matrix.rust-version }}
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust-version }}
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ matrix.rust-version }}
    - name: Run tests
      run: |
        cargo test --all-features

  publish:
    runs-on: ubuntu-latest
    needs: [test]
    environment: release
    steps:
    - uses: actions/checkout@v4
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
    - name: Publish to crates.io
      run: |
        cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}