name: Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-version: [stable, beta, nightly, "1.70.0"]
    steps:
    - uses: actions/checkout@v4
    - name: Setup Rust ${{ matrix.rust-version }}
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust-version }}
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ matrix.rust-version }}
    - name: Install dependencies
      run: |
        cargo fetch
    - name: Run tests
      run: |
        cargo test --all-features
    - name: Run clippy
      run: |
        cargo clippy -- -D warnings
      if: matrix.rust-version == 'stable'
    - name: Check formatting
      run: |
        cargo fmt --check
      if: matrix.rust-version == 'stable'